2020-08-11 23:04:58,830 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:50]
2020-08-11 23:18:54,952 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:50]
2020-08-12 00:00:42,278 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:51]
2020-08-12 22:12:26,986 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:51]
2020-08-12 23:20:37,858 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:51]
2020-08-13 10:52:11,291 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:52]
2020-08-14 15:41:03,854 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 15:42:36,143 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 15:44:32,580 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:00:14,475 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:00:33,863 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:02:13,798 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:02:27,444 ERROR: Exception on /reset_password_request [POST] [in c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\zyh\PycharmProjects\flask\application\routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\zyh\PycharmProjects\flask\application\email.py", line 24, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\zyh\PycharmProjects\flask\application\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'reset_password_request' instead?
2020-08-14 16:04:25,435 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:04:33,834 ERROR: Exception on /reset_password_request [POST] [in c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\zyh\PycharmProjects\flask\application\routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\zyh\PycharmProjects\flask\application\email.py", line 24, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\zyh\PycharmProjects\flask\application\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'reset_password_request' instead?
2020-08-14 16:06:05,777 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:07:50,382 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:11:31,748 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:28:16,459 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:32:43,853 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:34:04,477 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:35:28,324 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
