2020-08-14 16:35:35,641 ERROR: Exception on /reset_password_request [POST] [in c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\zyh\PycharmProjects\flask\application\routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\zyh\PycharmProjects\flask\application\email.py", line 25, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\zyh\PycharmProjects\flask\application\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'reset_password_request' instead?
2020-08-14 16:37:01,153 ERROR: Exception on /reset_password_request [POST] [in c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\zyh\PycharmProjects\flask\application\routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\zyh\PycharmProjects\flask\application\email.py", line 25, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\zyh\PycharmProjects\flask\application\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'reset_password_request' instead?
2020-08-14 16:37:33,014 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:48:45,923 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:48:50,973 ERROR: Exception on /reset_password_request [POST] [in c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\zyh\PycharmProjects\flask\application\routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\zyh\PycharmProjects\flask\application\email.py", line 30, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
TypeError: send_email() missing 1 required positional argument: 'html_body'
2020-08-14 16:49:24,237 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 16:53:14,360 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 17:02:40,340 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 17:04:06,502 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:55]
2020-08-14 17:54:52,791 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:60]
2020-08-14 18:28:20,269 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:63]
2020-08-14 18:29:09,996 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:63]
2020-08-14 18:30:36,952 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:63]
2020-08-14 18:35:11,597 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:63]
2020-08-14 18:44:55,514 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:64]
2020-08-14 18:49:03,671 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:64]
2020-08-14 18:50:11,273 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:64]
2020-08-15 18:24:46,511 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:64]
2020-08-15 19:39:33,056 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:64]
2020-08-15 19:40:30,276 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\flask\application\__init__.py:64]
